server:
  port: ${PORT:2024}
  servlet:
    session:
      timeout: 1d
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ArbitrageBroker
    key-store-type: PKCS12
    key-alias: arbitrage-broker.com
# Spring Boot configuration
spring:
  mail:
    debug: true
    host: smtp0101.titan.email
    username: admin@arbitrage-broker.com
    password: ehb=9Qx@UVul41>
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  application:
    name: eshop
    version: 0.0.1-SNAPSHOT
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  tomcat:
    uri-encoding: UTF-8
  messages:
    basename: i18n.messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    encoding: UTF-8
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://dbpostgresql:5432/eshop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:7nd2M487dMM7kLD4}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "UTC"
#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    enabled: false
site.url: arbitrage-broker.com
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: swagger
    enabled: true

#Logging
logging:
  file:
    path: logs/
    name: logs/app.log
    max-size: 20MB
    max-history: 180
    clean-history-on-start: true
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
      hibernate: ERROR
    guru:
      springframework:
        controllers: ERROR
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId:%X{traceId:-}, clientIp:%X{clientIp:-}, userId:%X{userId:-}] %logger{36} - %msg%n"
    rolling-file-name: logs/app-%d{yyyy-MM-dd-HH}.%i.log