server:
  port: ${PORT:2024}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ArbitrageBroker2024
    key-store-type: PKCS12
    key-alias: arbitrage-broker
# Spring Boot configuration
spring:
  application:
    name: eshop
    version: 0.0.1-SNAPSHOT
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  queries:
    users-query: select user_name, password, active_flag from tbl_user where user_name=?
    roles-query: select u.user_name, r.role from tbl_user u inner join tbl_user_role ur on (u.id=ur.user_id) inner join tbl_role r on (ur.role_id=r.id) where u.user_name=?
  tomcat:
    uri-encoding: UTF-8
  messages:
    basename: i18n.messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    encoding: UTF-8
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://dbpostgresql:5432/eshop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger

#Logging
logging:
  file:
    path: logs/
    name: logs/app.log
    max-size: 20MB
    max-history: 180
    clean-history-on-start: true
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
      hibernate: ERROR
    guru:
      springframework:
        controllers: ERROR
  pattern:
    console: _%d{yyyy-MMM-dd HH:mm:ss.SSS}{blue} %-5level [%thread] %logger{15} - %msg%n
    rolling-file-name: logs/app-%d{yyyy-MM-dd-HH}.%i.log