server:
  port: 2025
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ArbitrageBroker2024
    key-store-type: PKCS12
    key-alias: arbitrage-broker
  error:
    include-message: always
    include-binding-errors: always
# Spring Boot configuration
spring:
  application:
    name: client
    version: 0.0.1-SNAPSHOT
  queries:
    users-query: select user_name, password, active_flag from tbl_user where user_name=?
    roles-query: select u.user_name, r.role from tbl_user u inner join tbl_user_role ur on (u.id=ur.user_id) inner join tbl_role r on (ur.role_id=r.id) where u.user_name=?
  tomcat:
    uri-encoding: UTF-8
  messages:
    basename: i18n.messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    encoding: UTF-8
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://dbpostgresql:5432/eshop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
  mail:
    host: live.smtp.mailtrap.io
    username: api
    password: sdf
    port: 587
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enabled: true

site.url: arbitrage-broker.com
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger