#keytool -genkey -alias arbitrage-broker -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 365
server:
  port: 2025
spring:
  # Database
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eshop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
