-- ALTER USER postgres PASSWORD '7nd2M487dMM7kLD4';
-- CREATE SCHEMA IF NOT EXISTS eshop;
-- grant all privileges on database eshop to postgres;

-- CREATE ROLE eshop_user WITH LOGIN PASSWORD 'xmrtuKNbeE7O1kU';
-- GRANT ALL PRIVILEGES ON DATABASE eshop TO eshop_user;
-- ALTER ROLE eshop_user WITH NOSUPERUSER NOCREATEDB;
-- \c eshop
-- GRANT USAGE ON SCHEMA public TO eshop_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO eshop_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO eshop_user;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eshop_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eshop_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO eshop_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO eshop_user;


